#!/usr/bin/env python3
"""Append new leads to opportunities/leads.json."""
import json
from pathlib import Path
from datetime import datetime

PROJECT = Path("/Volumes/DATA/PROJECTS/TENDERS")
LEADS_JSON = PROJECT / "opportunities" / "leads.json"

NEW_LEADS = [
    {"institution_slug": "whc", "institution_name": "Ministry of Water Water Institute", "website_url": "https://whc.go.tz/", "emails": ["rector@waterinstitute.ac.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found. Site timed out. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Water Institute", "draft_email_body": "Dear Water Institute Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support the Water Institute. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "whitecity", "institution_name": "WHITE CITY INTERNATIONAL", "website_url": "https://whitecity.co.tz/", "emails": ["whitecitytz@whitecity.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on White City International website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & White City International", "draft_email_body": "Dear White City International Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support White City International. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "whiztanzania", "institution_name": "WhizzTanzania (YouTube)", "website_url": "https://www.whizztanzania.com/", "emails": ["admin@whizztanzania.com", "info@saifeehospital.co.tz"], "opportunity_type": "partner", "opportunity_description": "Tender URL points to YouTube. WhizzTanzania.com aggregates tenders. ZIMA could partner on tender listing or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & WhizzTanzania", "draft_email_body": "Dear WhizzTanzania Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your tender aggregation platform and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support WhizzTanzania. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "whiztz", "institution_name": "WhizzTanzania (whiztz)", "website_url": "https://www.whizztanzania.com/", "emails": ["admin@whizztanzania.com", "info@saifeehospital.co.tz"], "opportunity_type": "partner", "opportunity_description": "Tender URL points to YouTube. Same as whizztanzania. ZIMA could partner on tender listing or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & WhizzTanzania", "draft_email_body": "Dear WhizzTanzania Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your tender aggregation platform and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support WhizzTanzania. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "whizztz", "institution_name": "WhizzTanzania (whizztz)", "website_url": "https://www.whizztanzania.com/", "emails": ["admin@whizztanzania.com", "info@saifeehospital.co.tz"], "opportunity_type": "partner", "opportunity_description": "Tender URL points to YouTube. Same as whizztanzania. ZIMA could partner on tender listing or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & WhizzTanzania", "draft_email_body": "Dear WhizzTanzania Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your tender aggregation platform and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support WhizzTanzania. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "whoiswhotanzania", "institution_name": "whoswhotanzania", "website_url": "https://whoiswhotanzania.co.tz/", "emails": ["info@whoiswhotanzania.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found. Site timed out. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & whoswhotanzania", "draft_email_body": "Dear whoswhotanzania Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support whoswhotanzania. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wia", "institution_name": "WIA", "website_url": "https://wia.co.tz/", "emails": ["nyangu@wia.co.tz", "info@wia.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on WIA (ISP) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & WIA", "draft_email_body": "Dear WIA Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support WIA. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wib", "institution_name": "Wilmaar Insurance Brokers", "website_url": "https://wib.co.tz/", "emails": ["info@wib.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on Wilmaar Insurance Brokers website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Wilmaar Insurance Brokers", "draft_email_body": "Dear Wilmaar Insurance Brokers Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Wilmaar Insurance Brokers. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wilaki", "institution_name": "Wilaki", "website_url": "https://wilaki.co.tz/", "emails": [], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on Wilaki (mining/construction equipment) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Wilaki", "draft_email_body": "Dear Wilaki Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Wilaki. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wildaftanzania", "institution_name": "WiLDAF Tanzania", "website_url": "https://wildaftanzania.or.tz/", "emails": ["info@wildaftanzania.or.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on WiLDAF Tanzania (NGO) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & WiLDAF Tanzania", "draft_email_body": "Dear WiLDAF Tanzania Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support WiLDAF Tanzania. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wildernessencounters", "institution_name": "Wilderness Encounters Safaris", "website_url": "https://www.wildernessencounters.co.tz/", "emails": ["info@wildernessencounters.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on Wilderness Encounters Safaris website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Wilderness Encounters Safaris", "draft_email_body": "Dear Wilderness Encounters Safaris Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Wilderness Encounters Safaris. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wildernessexpedition", "institution_name": "Wilderness Expedition", "website_url": "https://wildernessexpedition.co.tz/", "emails": ["info@wildernessexpedition.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on Wilderness Expedition website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Wilderness Expedition", "draft_email_body": "Dear Wilderness Expedition Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Wilderness Expedition. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "willy", "institution_name": "Willy", "website_url": "https://willy.co.tz/", "emails": ["webmaster@willy.co.tz"], "opportunity_type": "sell", "opportunity_description": "Site suspended. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services when site is restored.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Willy", "draft_email_body": "Dear Willy Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Willy. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "winglink", "institution_name": "Winglink Travel", "website_url": "https://winglink.co.tz/", "emails": ["winglink@winglink.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on Winglink Travel website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Winglink Travel", "draft_email_body": "Dear Winglink Travel Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Winglink Travel. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "winnet", "institution_name": "WINNET INVESTMENT LTD", "website_url": "https://winnet.co.tz/", "emails": ["info@winnet.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on Winnet Investment (IT) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Winnet Investment", "draft_email_body": "Dear Winnet Investment Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Winnet Investment. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wintender", "institution_name": "Wintender", "website_url": "https://portal.wintender.tz", "emails": ["info@wintender.co.tz"], "opportunity_type": "partner", "opportunity_description": "Wintender portal requires login. Tender consultancy platform. ZIMA could partner on tender listing or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Wintender", "draft_email_body": "Dear Wintender Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your tender consultancy platform and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Wintender. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "winther", "institution_name": "Winther Ltd", "website_url": "https://winther.co.tz/", "emails": [], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on Winther Ltd (joinery) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Winther Ltd", "draft_email_body": "Dear Winther Ltd Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Winther Ltd. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wipahs", "institution_name": "WIPAHS", "website_url": "https://wipahs.co.tz/", "emails": ["info@wipahs.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on WIPAHS (NGO) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & WIPAHS", "draft_email_body": "Dear WIPAHS Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support WIPAHS. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wisefutures", "institution_name": "Wise Futures", "website_url": "https://www.wisefutures.ac.tz/", "emails": ["wise.admin@nm-aist.ac.tz", "info@wisefutures.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on Wise Futures (academic) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Wise Futures", "draft_email_body": "Dear Wise Futures Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Wise Futures. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wizdon", "institution_name": "Wizdon", "website_url": "https://wizdon.co.tz/", "emails": ["info@wizdon.co.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on Wizdon (ICT) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Wizdon", "draft_email_body": "Dear Wizdon Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Wizdon. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wleetngo", "institution_name": "WLEET", "website_url": "https://wleetngo.or.tz/", "emails": ["info@wleetngo.or.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on WLEET (NGO) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & WLEET", "draft_email_body": "Dear WLEET Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support WLEET. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wma", "institution_name": "Weight and Measurement Agency - WMA", "website_url": "https://www.wma.go.tz/", "emails": ["info@wma.go.tz"], "opportunity_type": "sell", "opportunity_description": "No active tenders found on WMA website. Has publications and announcements. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & WMA", "draft_email_body": "Dear WMA Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support WMA. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wmpso", "institution_name": "Wings of Mercy's", "website_url": "https://wmpso.or.tz/", "emails": ["info@wmpso.or.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found. Site timed out. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Wings of Mercy's", "draft_email_body": "Dear Wings of Mercy's Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support Wings of Mercy's. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
    {"institution_slug": "wodsta", "institution_name": "Wodsta", "website_url": "https://wodsta.or.tz/", "emails": ["wodstatz@wodsta.or.tz"], "opportunity_type": "sell", "opportunity_description": "No formal tenders found on WODSTA (NGO) website. ZIMA Solutions could offer digital transformation, fintech integrations, or ICT services.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & WODSTA", "draft_email_body": "Dear WODSTA Team,\n\nZIMA Solutions Limited specialises in digital transformation for financial institutions and enterprises in Tanzania. We noticed your organisation and believe we could support your technology and innovation goals.\n\nOur offerings include:\n• GePG, TIPS, and RTGS integrations\n• SACCO and microfinance systems\n• AI-powered customer engagement\n• HR, school, and healthcare management systems\n\nWe would welcome a conversation about how we might support WODSTA. Could we schedule a brief call?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n", "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z", "status": "pending"},
]

def main():
    leads = []
    if LEADS_JSON.exists():
        with open(LEADS_JSON) as f:
            data = json.load(f)
        leads = data if isinstance(data, list) else data.get("leads", [])

    existing_slugs = {l.get("institution_slug") for l in leads}
    added = 0
    for lead in NEW_LEADS:
        if lead["institution_slug"] not in existing_slugs:
            leads.append(lead)
            existing_slugs.add(lead["institution_slug"])
            added += 1

    with open(LEADS_JSON, "w", encoding="utf-8") as f:
        json.dump(leads, f, indent=2, ensure_ascii=False)

    print(f"Appended {added} new leads. Total: {len(leads)}")

if __name__ == "__main__":
    main()
