#!/usr/bin/env python3
"""Append batch leads from run_20260315_060430_batch78 to opportunities/leads.json."""
import json
from pathlib import Path
from datetime import datetime

PROJECT = Path("/Volumes/DATA/PROJECTS/TENDERS")
LEADS_JSON = PROJECT / "opportunities" / "leads.json"

NEW_LEADS = [
    {"institution_slug": "mpwapwadc", "institution_name": "Mpwapwa District Council", "website_url": "https://mpwapwadc.go.tz/manunuzi-na-ugavi", "emails": ["info@mpwapwadc.go.tz"], "opportunity_type": "sell", "opportunity_description": "Site timed out during scrape. LGA with procurement page. ZIMA could offer GePG, digital procurement, or ICT systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Mpwapwa District Council", "draft_email_body": "Dear Mpwapwa District Council,\n\nZIMA Solutions Limited specialises in digital transformation for government agencies in Tanzania. We noticed your procurement activities and believe we could support your digital operations.\n\nOur offerings include GePG integration, digital procurement systems, and ICT infrastructure. We would welcome a conversation.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mpwapwatc", "institution_name": "Mpwapwa Teachers College", "website_url": "https://mpwapwatc.ac.tz/", "emails": ["webmaster@mpwapwatc.ac.tz"], "opportunity_type": "sell", "opportunity_description": "Account suspended. Educational institution. ZIMA could offer school management, ICT, or digital systems when site is restored.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Mpwapwa Teachers College", "draft_email_body": "Dear Mpwapwa Teachers College,\n\nZIMA Solutions Limited specialises in digital transformation for educational institutions. We would welcome a conversation about school management systems and ICT solutions.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mrhp", "institution_name": "Mwanza Rural Housing Programme", "website_url": "https://mrhp.or.tz/", "emails": [], "opportunity_type": "sell", "opportunity_description": "Page not found (404). NGO. ZIMA could offer housing/finance systems, digital tools when site is updated.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & MRHP", "draft_email_body": "Dear MRHP Team,\n\nZIMA Solutions Limited specialises in digital transformation for NGOs. We would welcome a conversation about ICT and digital solutions.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mrimbapalmhotel", "institution_name": "Mrimba Palm Hotel", "website_url": "https://mrimbapalmhotel.co.tz/", "emails": [], "opportunity_type": "sell", "opportunity_description": "Hotel in Arusha. No tenders. ZIMA could offer property management, payment systems, or digital booking.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Mrimba Palm Hotel", "draft_email_body": "Dear Mrimba Palm Hotel,\n\nZIMA Solutions Limited specialises in digital transformation for hospitality. We could support payment systems, property management, or booking solutions.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mrishoconsult", "institution_name": "Mrisho Consult Ltd", "website_url": "https://mrishoconsult.co.tz/", "emails": ["info@mrishoconsult.co.tz"], "opportunity_type": "sell", "opportunity_description": "Real estate/land consultancy. No tenders. ZIMA could offer CRM, digital documentation, or fintech for property transactions.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Mrisho Consult", "draft_email_body": "Dear Mrisho Consult,\n\nZIMA Solutions Limited specialises in digital transformation for enterprises. We could support your land consultancy with CRM, document management, or payment solutions.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mrutuagrosolutions", "institution_name": "Mrutu Agro Solutions", "website_url": "https://mrutuagrosolutions.co.tz/", "emails": ["info@MrutuAgroSolutions.co.tz"], "opportunity_type": "sell", "opportunity_description": "Agribusiness. No tenders. ZIMA could offer AgriSave-style digital savings, farmer finance, or supply chain systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Mrutu Agro Solutions", "draft_email_body": "Dear Mrutu Agro Solutions,\n\nZIMA Solutions Limited specialises in digital solutions for agribusiness. We could support farmer finance, digital savings, or supply chain systems.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msafiriexpress", "institution_name": "Msafiri Express", "website_url": "https://msafiriexpress.co.tz/", "emails": ["webmaster@msafiriexpress.co.tz"], "opportunity_type": "sell", "opportunity_description": "Account suspended. Transport/logistics. ZIMA could offer ticketing, payment, or fleet systems when site is restored.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Msafiri Express", "draft_email_body": "Dear Msafiri Express,\n\nZIMA Solutions Limited specialises in digital transformation for transport. We could support ticketing, payments, or fleet management.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msameja", "institution_name": "MS Consult", "website_url": "https://www.msameja.co.tz/", "emails": ["consult@msameja.co.tz"], "opportunity_type": "sell", "opportunity_description": "Strategy/operations consultancy. No tenders. ZIMA could partner on ICT projects or offer digital tools.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & MS Consult", "draft_email_body": "Dear MS Consult,\n\nZIMA Solutions Limited specialises in digital transformation. We could partner on ICT projects or support your consultancy with digital tools.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mscl", "institution_name": "TASHICO", "website_url": "https://www.tashico.co.tz/", "emails": ["info@tashico.co.tz"], "opportunity_type": "sell", "opportunity_description": "Tanzania Shipping Company. No tenders on homepage. ZIMA could offer cargo/logistics systems, GePG, or ICT.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & TASHICO", "draft_email_body": "Dear TASHICO,\n\nZIMA Solutions Limited specialises in digital transformation for logistics. We could support cargo systems, payments, or ICT infrastructure.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msekeni", "institution_name": "Msekeni Inc", "website_url": "https://msekeni.co.tz/", "emails": ["info@msekeni.co.tz"], "opportunity_type": "sell", "opportunity_description": "Procurement/R&D consultancy. No tenders. ZIMA could partner on ICT procurement or offer digital systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Msekeni Inc", "draft_email_body": "Dear Msekeni Inc,\n\nZIMA Solutions Limited specialises in digital transformation. We could partner on ICT procurement or support your operations with digital systems.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mservices", "institution_name": "M Services", "website_url": "https://mservices.co.tz/", "emails": ["info@mservices.co.tz"], "opportunity_type": "sell", "opportunity_description": "Electrical contractor. No tenders. ZIMA could offer project management, invoicing, or solar monitoring systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & M Services", "draft_email_body": "Dear M Services,\n\nZIMA Solutions Limited specialises in digital solutions for contractors. We could support project management, invoicing, or solar monitoring.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msichana", "institution_name": "Msichana Initiative", "website_url": "https://msichana.or.tz/", "emails": [], "opportunity_type": "sell", "opportunity_description": "NGO for girls' rights. No tenders. ZIMA could offer donor management, digital tools, or financial inclusion systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Msichana Initiative", "draft_email_body": "Dear Msichana Initiative,\n\nZIMA Solutions Limited specialises in digital solutions for NGOs. We could support donor management, digital tools, or financial inclusion.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msminvestment", "institution_name": "MSM Autos & Investment Ltd", "website_url": "https://msminvestment.co.tz/", "emails": [], "opportunity_type": "sell", "opportunity_description": "Auto/investment company. No tenders. ZIMA could offer inventory, finance, or CRM systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & MSM Investment", "draft_email_body": "Dear MSM Investment,\n\nZIMA Solutions Limited specialises in digital transformation. We could support inventory, finance, or CRM systems for your operations.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msoft", "institution_name": "MSOFT Limited", "website_url": "https://www.msoft.co.tz/", "emails": ["sales@msoft.co.tz"], "opportunity_type": "partner", "opportunity_description": "IT company (networks, VoIP, security). No tenders. ZIMA could partner on projects or integrate solutions.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & MSOFT", "draft_email_body": "Dear MSOFT,\n\nZIMA Solutions Limited specialises in digital transformation. We see potential for partnership on ICT projects in Tanzania. Could we explore collaboration?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msomeni", "institution_name": "MSOMENI BLOG", "website_url": "https://www.msomeni.co.tz/", "emails": [], "opportunity_type": "sell", "opportunity_description": "Educational blog. No tenders. ZIMA could offer school management or e-learning platforms.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & MSOMENI", "draft_email_body": "Dear MSOMENI,\n\nZIMA Solutions Limited offers school management and e-learning solutions. We would welcome a conversation.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msongolainstitute", "institution_name": "Msongola Health Training Institute", "website_url": "https://www.msongolainstitute.ac.tz/", "emails": [], "opportunity_type": "sell", "opportunity_description": "Health training institute. No tenders. ZIMA could offer school/healthcare management systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Msongola Institute", "draft_email_body": "Dear Msongola Institute,\n\nZIMA Solutions Limited offers school and healthcare management systems. We would welcome a conversation.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msosiexpress", "institution_name": "MsosiExpress", "website_url": "https://msosiexpress.co.tz/", "emails": [], "opportunity_type": "sell", "opportunity_description": "Fresh food delivery. Site timed out. ZIMA could offer delivery/payment or inventory systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & MsosiExpress", "draft_email_body": "Dear MsosiExpress,\n\nZIMA Solutions Limited specialises in digital solutions for delivery businesses. We could support payments or inventory systems.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mstj", "institution_name": "MSTJ Traders Limited", "website_url": "https://mstj.co.tz/", "emails": ["info@mstj.co.tz"], "opportunity_type": "sell", "opportunity_description": "Logistics/clearing & forwarding. No tenders. ZIMA could offer cargo, customs, or payment systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & MSTJ Traders", "draft_email_body": "Dear MSTJ Traders,\n\nZIMA Solutions Limited specialises in digital solutions for logistics. We could support cargo, customs, or payment systems.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "msumbanews", "institution_name": "MSUMBA NEWS BLOG", "website_url": "https://www.msumbanews.co.tz/", "emails": ["info@ishimax.co.tz"], "opportunity_type": "sell", "opportunity_description": "News blog. No tenders. ZIMA could offer digital publishing or payment systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & MSUMBA NEWS", "draft_email_body": "Dear MSUMBA NEWS,\n\nZIMA Solutions Limited offers digital solutions for media. We would welcome a conversation.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mtaakwamtaa", "institution_name": "MTAA KWA MTAA BLOG", "website_url": "http://www.mtaakwamtaa.co.tz/", "emails": ["info@mkcomputertweaks.net"], "opportunity_type": "sell", "opportunity_description": "Blog. No tenders. ZIMA could offer digital solutions.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & MTAA KWA MTAA", "draft_email_body": "Dear MTAA KWA MTAA,\n\nZIMA Solutions Limited offers digital solutions. We would welcome a conversation.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mtaji", "institution_name": "Mtaji", "website_url": "https://www.mtaji.co.tz/", "emails": ["mtaji@mtaji.co.tz", "sales@mtaji.co.tz"], "opportunity_type": "partner", "opportunity_description": "MSME financing. No tenders. ZIMA could partner on fintech, loan management, or VICOBA integration.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Mtaji", "draft_email_body": "Dear Mtaji,\n\nZIMA Solutions Limited specialises in fintech and loan management systems. We see potential for partnership on MSME financing. Could we explore collaboration?\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mtendelehotel", "institution_name": "Mtendele Hotel", "website_url": "https://mtendelehotel.co.tz/", "emails": ["mtendelehotel@yahoo.com", "info@mtendelehotel.co.tz"], "opportunity_type": "sell", "opportunity_description": "Hotel in Tanga. No tenders. ZIMA could offer property management or payment systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Mtendele Hotel", "draft_email_body": "Dear Mtendele Hotel,\n\nZIMA Solutions Limited specialises in digital solutions for hospitality. We could support property management or payments.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
    {"institution_slug": "mtmerugamelodge", "institution_name": "Mount Meru Game Lodge", "website_url": "https://mountmerugamelodge.co.tz/", "emails": ["info@mtmerugamelodge.co.tz", "reservations@mtmerugamelodge.co.tz"], "opportunity_type": "sell", "opportunity_description": "Safari lodge. No tenders. ZIMA could offer booking, payment, or property management systems.", "draft_email_subject": "Partnership Opportunity – ZIMA Solutions & Mount Meru Game Lodge", "draft_email_body": "Dear Mount Meru Game Lodge,\n\nZIMA Solutions Limited specialises in digital solutions for hospitality. We could support booking, payments, or property management.\n\nBest regards,\nZIMA Solutions Limited\ninfo@zima.co.tz | +255 69 241 0353\n"},
]

def main():
    now = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    for lead in NEW_LEADS:
        lead["created_at"] = now
        lead["status"] = "pending"

    leads = []
    if LEADS_JSON.exists():
        with open(LEADS_JSON) as f:
            data = json.load(f)
        leads = data if isinstance(data, list) else data.get("leads", [])

    existing_slugs = {l.get("institution_slug") for l in leads}
    appended = 0
    for lead in NEW_LEADS:
        if lead["institution_slug"] not in existing_slugs:
            leads.append(lead)
            existing_slugs.add(lead["institution_slug"])
            appended += 1

    with open(LEADS_JSON, "w", encoding="utf-8") as f:
        json.dump(leads, f, indent=2, ensure_ascii=False)

    print(f"Appended {appended} new leads. Total: {len(leads)}")

if __name__ == "__main__":
    main()
